### ISSUE TITLE
[BUG] Blank screen with weekly timetable

### ISSUE THREAD

**Issue by TuxedoFish** [uclapi/ucl-assistant-app#451]
**Describe the bug**
When merging in the weekly timetable, there was a blank screen. Not entirerly sure why this happened so will describe anything I notice!

**To Reproduce**
1. Have assistant app in state it would have been with master before pr
2. update branch to latest and open the app
3. app will load only to have blank screen

**Expected behavior**
Should function as normal 

**Screenshots**

**Please provide the following information:**
 - Release Channel [check Settings]

**Additional context**

**Comment by hueyy** [comment]
The issue seems to be some error in the native Java code. Some variation of this error message intermittently pops up in production mode:

>Uncaught Error: Error while updating property [attribute] in shadow node of type: [component]

For example

>Uncaught Error: Error while updating property 'width' in shadow node of type: RCTView

This error is known to occur when a fractional value is set for width/height/padding/etc, or when a value of the wrong type is passed (e.g. string instead of integer for width). But as far as I can tell, we don't do that at all.
