### ISSUE TITLE
Build Failing with React Navigation Errors

### ISSUE THREAD

**Issue by ChristopherHammond13** [uclapi/ucl-assistant-app#6]
![image](https://user-images.githubusercontent.com/295396/52649215-ce958180-2edf-11e9-80b8-a097e2c32af9.png)
I have no idea what's causing this so I'm open to suggestion. It could well be my terrible local build environment though (I have many a Node issue...)

**Comment by hueyy** [comment]
At first glance this looks like a react-navigation v2/v3 compatibility issue because v3 now uses `createAppContainer` instead of `createNavigationContainer` ([see issue](https://github.com/react-navigation/react-navigation/issues/5222)).

I've already updated the navigation in the app to use `createAppContainer` so this error is really strange. I would suggest:

(a) checking that you're on the master branch updated with the latest commits (but you're almost certainly there because you pushed the commits) and

(b) removing and readding react-navigation v3 (maybe even try deleting node_modules altogether and reinstalling the dependencies) if you haven't already tried that.

I'll try to reproduce the issue, but I'm pretty stumped 😕.

**Comment by ChristopherHammond13** [comment]
That sounds about right but no joy :( I did another git pull from master and I'm up to date so I'm doing another `rm -rf node_modules` and I'll try and `npm i` those again

**Comment by ChristopherHammond13** [comment]
Ok I fixed it! It was this bug fix: https://github.com/react-navigation/react-navigation/issues/5222#issuecomment-439805038
